import { MissingOptionalDependencyError } from "./error";

// ────────────────────────────────────────────────────────────────
// Lazy-loaded optional dependencies
// ────────────────────────────────────────────────────────────────
// jszip is only needed by toZIP()/fromZIP() — every other method on
// MajikKeyBackup (create, fromJSON, fromPNG, toJSON) never touches it,
// so no consumer pays for it unless they actually use the zip feature.
// Note: in bundled contexts (Vite/webpack/etc.) `import("jszip")` still
// needs jszip resolvable at build time — this buys code-splitting
// (its own lazy-fetched chunk), not "works with zero jszip installed".
// In plain-Node consumers (CLI, MCP server) it genuinely defers
// resolution to runtime, and throws the typed error below if absent.

// eslint-disable-next-line @typescript-eslint/no-explicit-any
let _jszip: any | null = null;

export async function getJSZip(): Promise<any> {
  if (_jszip) return _jszip;
  try {
    const mod: any = await import("jszip");
    _jszip = mod.default ?? mod;
  } catch {
    throw new MissingOptionalDependencyError(
      "jszip",
      "read or write .zip backups",
    );
  }
  return _jszip;
}

// @majikah/majik-bytes is a hard dependency of this library (Josef
// controls it), so this loader exists purely to keep the import
// pattern consistent with getJSZip() — not for optionality.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
let _majikBytes: any | null = null;

export async function getMajikBytes(): Promise<any> {
  if (_majikBytes) return _majikBytes;
  _majikBytes = await import("@majikah/majik-bytes");
  return _majikBytes;
}

// ────────────────────────────────────────────────────────────────
// Binary sniffing — classify by magic bytes, never by file extension
// ────────────────────────────────────────────────────────────────

const PNG_MAGIC = [0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a];

export function looksLikePNG(bytes: Uint8Array): boolean {
  if (bytes.length < PNG_MAGIC.length) return false;
  return PNG_MAGIC.every((byte, i) => bytes[i] === byte);
}

/** Zip local-file-header signature ("PK\x03\x04"), also covers empty-archive/spanned variants starting "PK". */
export function looksLikeZip(bytes: Uint8Array): boolean {
  return bytes.length > 2 && bytes[0] === 0x50 && bytes[1] === 0x4b;
}

// ────────────────────────────────────────────────────────────────
// Encoding helpers
// ────────────────────────────────────────────────────────────────


export function toSafeFileName(value: string): string {
  return value
    .replace(/[<>:"/\\|?*\x00-\x1F]/g, "-")
    .replace(/\s+/g, " ")
    .trim()
    .replace(/[. ]+$/, "");
}

// ────────────────────────────────────────────────────────────────
// README — centralized so copy updates happen in exactly one place
// ────────────────────────────────────────────────────────────────

/**
 * Static body of the backup README. Update this whenever the copy
 * needs to change — every zip generated by toZIP() picks it up
 * automatically, nothing else needs to change.
 */
export const README_TEXT = `Majik Key Backup

IMPORTANT: Keep this file secure and private at all times. If lost or compromised, your account access may be permanently at risk.

Overview
This backup ZIP file contains your raw JSON data and a Backup PNG. These files are essential for recovering your account.

Usage Instructions
- Storage: You may delete the JSON file and keep only the PNG file if preferred.
- Customization: You can rename the PNG file for added discretion.
- Recovery: This PNG allows you to securely re-import your account without exposing raw JSON data.

Critical Handling Requirements
To prevent data corruption and ensure the backup remains functional, please follow these rules:

- No Modifications: Do not edit, crop, or apply filters to the PNG image.
- No Processing: Avoid running the image through compression tools or "optimization" software.
- Storage Only: Store the image as is. Do not upload it to social media, messaging apps, or cloud platforms that automatically compress or manipulate images, as this will destroy the embedded data.

IMPORTANT: Keep this file secure and private at all times. If lost or compromised, your account access may be permanently at risk.`;

/** README_TEXT plus a creation timestamp line — the only per-backup variable part. */
export function buildReadmeText(createdAt: Date = new Date()): string {
  return `${README_TEXT}\n\nBackup created on: ${createdAt.toLocaleString()}\n`;
}
